In [1]:
import sys
sys.path.append("../../smsl")

In [2]:
from smsl.graphBigtraj import BigTrajGraphAgent
from smsl.graph import ST_BOT

import warnings; warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd

In [3]:
## 見論文表B.7
n_mode=30         ## $\alpha_c$
vlv_threshold=0.1 ## $\nu_{\text{c}}$
pe_threshold=0.6  ## $\kappa_{\text{c}}$

In [4]:
b_agent = BigTrajGraphAgent(ST_BOT)

Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/0000_0500/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/0250_0750/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/0500_1000/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/0750_1250/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/1000_1500/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/1250_1750/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/1500_2000/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/1750_2250/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/2000_2500/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/2250_2750/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/2500_3000/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/2750_3250/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/3000_3500/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/3250_3750/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/3500_4000/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/3750_4250/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/4000_4500/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/4250_4750/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/4500_5000/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/0000_5000/result/pairtypes_k_b0_cutoff_5.00.csv

In [5]:
b_agent.spectral_decomposition()
b_agent.set_mean_r_alpha_array()
b_agent.t_agent.mean.GetEigenvectorEigenvectorT()

Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 132 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.

In [6]:
## 論文 圖5.21(B)
b_agent.plot_prominent_modes_and_identify_atom_with_interactive(strandid=None)

interactive(children=(IntSlider(value=1, description='sele_mode', max=132, min=1), Output()), _dom_classes=('w…

In [7]:
b_agent.plot_prominent_modes_and_get_identify_pair_with_interactive(\
        strandid=None, vlv_threshold=vlv_threshold, pe_threshold=pe_threshold, filter=True)

interactive(children=(IntSlider(value=1, description='sele_mode', max=132, min=1), Output()), _dom_classes=('w…

In [8]:
b_agent.t_agent.mean.get_modes_info(strandid=None, n_mode=n_mode, vlv_threshold=vlv_threshold, pe_threshold=pe_threshold, is_return=False)

100%|██████████| 30/30 [00:00<00:00, 55.81it/s]

In [9]:
b_agent.t_agent.mean.df_info_by_modes

,mode,lambda,hotspot_atom,0,1,2,3
1,1,27.1,C2(G15),C2C5(G15G16),N3C5(G15G16),C2C4(G15G16),
2,2,24.5,C2(G3),C2C5(G3G4),N1C5(G3G4),C2C4(G3G4),
3,3,21.3,N3(G15),N3N7(G15G16),C4N7(G15G16),,
4,4,19.6,N3(G3),N3N7(G3G4),C4N7(G3G4),,
5,5,18.8,C5(G20),C2C5(G21G20),C6C5(G21G20),N1C4(G21G20),C2C4(G21G20)
6,6,16.9,N1(G3),N1C6(G3G4),C6C6(G3G4),,
7,7,16.1,N1(G15),N1C6(G15G16),N1N1(G15G16),N1O6(G15G16),
8,8,15.7,C5(G8),N1C5(G9G8),C2C5(G9G8),N1C6(G9G8),N1C4(G9G8)
9,9,13.3,C2(G8),N7C2(G15G8),N7N2(G15G8),C4N2(G15G8),
10,10,13.2,C2(G21),N1C6(G21G20),,,
11,11,12.8,N7(G20),C2C4(G21G20),N3N7(G21G20),C6N7(G21G20),
12,12,12.7,C4(G3),N3C8(G3G4),N3C4(G3G4),N3N9(G3G4),
13,13,12.6,N3(G15),C4N7(G15G16),N7C2(G15G8),,
14,14,12.2,C6(G3),C2C4(G3G4),N1C5(G3G4),,
15,15,12.0,C2(G16),N7C2(G21G16),N7N2(G21G16),N7N1(G21G16),
16,16,11.1,C5(G20),C6C5(G21G20),N3N7(G21G20),N3C4(G21G20),
17,17,11.1,C5(G16),N2C4(G15G16),C2C4(G15G16),,
18,18,10.3,N1(G9),C2C4(G9G8),C2C5(G9G8),N1N1(G9G8),
19,19,10.0,C6(G3),,,,
20,20,9.6,N1(G8),C6N1(G15G8),,,
21,21,8.9,N7(G20),C6N7(G21G20),C5N7(G21G20),N3C5(G21G20),N3C8(G21G20)
22,22,8.6,C2(G8),C8N2(G15G8),,,
23,23,8.5,C2(G15),N2C5(G15G16),,,
24,24,8.3,N7(G3),N7N2(G3G20),C5N2(G3G20),N7C2(G3G20),C5C2(G3G20)
25,25,7.8,C6(G20),C6C6(G21G20),C5C5(G21G20),C5N2(G21G16),
26,26,7.5,C5(G8),N2C4(G9G8),N1C4(G9G8),,
27,27,6.9,N1(G16),C5N1(G21G16),,,
28,28,6.8,C2(G3),N2C4(G3G4),N2C5(G3G4),,
29,29,6.6,C6(G16),,,,
30,30,6.2,C6(G20),N2C4(G21G20),,,

In [10]:
## 論文 圖5.22(C)
b_agent.t_agent.mean.display_df_info_by_resid(save=True)

Write /home/user/workfolder/g4dna_protocol_demo/chair/d.fluctmatch/bigtraj_fluctmatch/0000_5000/result/chair_ST_BOT.csv

In [11]:
hotspot_pair_num = 8
## Summaries aiaj
atom_pairs_all_resid = {}
for gstrand_layer, modes_info in b_agent.t_agent.mean.df_info_by_resid.iterrows():
    if not 'ss_st' in gstrand_layer: continue
    atom_pairs_all_resid.setdefault(gstrand_layer, [])
    for mode_info in modes_info:
        atom_pairs = mode_info.split()
        atom_pairs = atom_pairs[2:]
        atom_pairs = [atom_pair.split('(')[0] for atom_pair in atom_pairs]
        atom_pairs_all_resid[gstrand_layer] += atom_pairs
## count aiaj and select highest 7 aiaj as hotspot pair
atom_pairs_count = list(atom_pairs_all_resid.values())
atom_pairs_count = [a for ap in atom_pairs_count for a in ap]
atom_pairs_count = np.unique(atom_pairs_count, return_counts=True)
atom_pairs_count = {atom_pair: count for atom_pair, count in zip(atom_pairs_count[0], atom_pairs_count[1])}
atom_pairs_count = dict(sorted(atom_pairs_count.items(), key=lambda x:x[1], reverse=True))
df_hotspot_pairs = pd.DataFrame([atom_pairs_count.keys(),atom_pairs_count.values()], index=[r'$\rm{a}_{i}\rm{a}_{j}$','count']).T
df_hotspot_pairs.index = range(1, len(df_hotspot_pairs)+1)
df_hotspot_pairs['hotspot'] = ''
df_hotspot_pairs.loc[df_hotspot_pairs.index[:hotspot_pair_num], 'hotspot'] = 'v'

In [12]:
df_hotspot_pairs

   $\rm{a}_{i}\rm{a}_{j}$ count hotspot
1                    C2C4     7       v
2                    C2C5     5       v
3                    N1C6     4       v
4                    N2C4     4       v
5                    N3N7     4       v
6                    C4N7     3       v
7                    N1C4     3       v
8                    N1C5     3       v
9                    C6C5     2
10                   C6C6     2
11                   C6N7     2
12                   N1N1     2
13                   N2C5     2
14                   N3C4     2
15                   N3C5     2
16                   N3C8     2
17                   C5C5     1
18                   C5N2     1
19                   C5N7     1
20                   N1O6     1
21                   N3N9     1
22                   N7C2     1

In [13]:
## 確認機械熱點原子對的機械強度k_ij是否較高
b_agent.t_agent.mean.df_m.sort_values(by='k', ascending=False)

,Enm_i,Strand_i,Resid_i,Atomname_i,Atomid_i,Enm_j,Strand_j,Resid_j,Atomname_j,Atomid_j,k,b0,Category
PairID,,,,,,,,,,,,,
5600,A310,STRAND1,15,C2,310,A328,STRAND1,16,C5,328,8.702811,3.445737,ss_st
1187,A56,STRAND1,3,C2,56,A74,STRAND1,4,C5,74,7.271063,3.500384,ss_st
1285,A59,STRAND1,3,C4,59,A73,STRAND1,4,N7,73,6.603305,3.401579,ss_st
5673,A312,STRAND1,15,N3,312,A327,STRAND1,16,N7,327,5.979058,3.410168,ss_st
5695,A313,STRAND1,15,C4,313,A327,STRAND1,16,N7,327,5.621326,3.476221,ss_st
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5476,A304,STRAND1,15,C8,304,A330,STRAND1,16,O6,330,0.000000,5.312958,ss_st
5475,A304,STRAND1,15,C8,304,A328,STRAND1,16,C5,328,0.000000,5.235126,ss_st
5474,A304,STRAND1,15,C8,304,A327,STRAND1,16,N7,327,0.000000,4.442600,ss_st
5473,A304,STRAND1,15,C8,304,A326,STRAND1,16,C8,326,0.000000,5.048000,ss_st
975,A49,STRAND1,3,N9,49,A71,STRAND1,4,N9,71,0.000000,4.948763,ss_st