In [1]:
import sys
sys.path.append("../../smsl")

In [2]:
from smsl.graphBigtraj import BigTrajGraphAgent
from smsl.graph import HB

import warnings; warnings.filterwarnings("ignore")
import numpy as np

In [3]:
## 見論文表B.7
n_mode=30         ## $\alpha_c$
vlv_threshold=0.1 ## $\nu_{\text{c}}$
pe_threshold=0.6  ## $\kappa_{\text{c}}$

In [4]:
b_agent = BigTrajGraphAgent(HB)

Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/0000_0500/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/0250_0750/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/0500_1000/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/0750_1250/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/1000_1500/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/1250_1750/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/1500_2000/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/1750_2250/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/2000_2500/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/2250_2750/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/2500_3000/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/2750_3250/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/3000_3500/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/3250_3750/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/3500_4000/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/3750_4250/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/4000_4500/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/4250_4750/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/4500_5000/result/pairtypes_k_b0_cutoff_5.00.csv
Reading data from: /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/0000_5000/result/pairtypes_k_b0_cutoff_5.00.csv

In [5]:
b_agent.spectral_decomposition()
b_agent.set_mean_r_alpha_array()
b_agent.t_agent.mean.GetEigenvectorEigenvectorT()

Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.
Thare are 418 nodes.
Initialize adjacency, degree and Laplacian matrices... Done.
Finish the setup for Laplaican matrix.

In [6]:
## 論文 圖5.20(A)
b_agent.plot_prominent_modes_and_identify_atom_with_interactive(strandid=None)

interactive(children=(IntSlider(value=1, description='sele_mode', max=418, min=1), Output()), _dom_classes=('w…

In [7]:
b_agent.plot_prominent_modes_and_get_identify_pair_with_interactive(\
        strandid=None, vlv_threshold=vlv_threshold, pe_threshold=pe_threshold, filter=True)

interactive(children=(IntSlider(value=1, description='sele_mode', max=418, min=1), Output()), _dom_classes=('w…

In [8]:
b_agent.t_agent.mean.get_modes_info(strandid=None, n_mode=n_mode, vlv_threshold=vlv_threshold, pe_threshold=pe_threshold, is_return=False)

100%|██████████| 30/30 [00:00<00:00, 72.43it/s]

In [9]:
b_agent.t_agent.mean.df_info_by_modes

   mode lambda hotspot_atom             0             1             2
1     1   34.5       O2(C7)   N2O2(G16C7)
2     2   34.4      N2(G10)  N2O2(G10C13)
3     3   33.1       N2(G4)   N2O2(G4C19)
4     4   31.8       N2(G9)   N2O2(G9C14)   N2C2(G9C14)
5     5   31.8       O2(C8)   N2O2(G15C8)   N2C2(G15C8)
6     6   31.8       N2(G8)   N2O2(G8C15)
7     7   31.6       O2(C9)   N2O2(G14C9)
8     8   31.4       O2(C2)   N2O2(G21C2)   N2C2(G21C2)
9     9   30.3       N2(G3)   N2O2(G3C20)
10   10   28.9       O2(C3)   N2O2(G20C3)
11   11   26.9      C2(G10)  C2C2(G10C13)
12   12   26.7       C2(C7)   C2C2(G16C7)
13   13   26.1       C2(G4)   C2C2(G4C19)
14   14   25.8       C2(C9)   C2C2(G14C9)
15   15   25.0       C2(G8)   C2C2(G8C15)
16   16   24.4       N1(G4)   N1N3(G4C19)
17   17   24.3       N1(A6)   N3N1(T17A6)   C4N1(T17A6)
18   18   24.1      N1(G10)  N1N3(G10C13)  C6N3(G10C13)  N1N4(G10C13)
19   19   23.9       C2(G3)   C2C2(G3C20)
20   20   22.9       N3(T5)   N3N1(T5A18)   C4N1(T5A18)
21   21   22.9       N3(C7)   N1N3(G16C7)   C6N3(G16C7)   N1N4(G16C7)
22   22   22.5       N1(G8)   N1N3(G8C15)   N1N4(G8C15)
23   23   22.4       N3(C9)   N1N3(G14C9)   N1N4(G14C9)
24   24   22.2       N1(G9)   N1N3(G9C14)
25   25   22.1       N2(G2)   N2O2(G2C21)   C2C2(G2C21)
26   26   22.0      N3(T11)  N3N1(T11A12)  O4N1(T11A12)  C4N1(T11A12)
27   27   21.2       C2(C3)   C2C2(G20C3)
28   28   20.9       C2(C8)   C2C2(G15C8)
29   29   20.3       N3(C3)   N1N3(G20C3)
30   30   20.2       C2(C2)   C2C2(G21C2)

In [11]:
## 論文 圖5.20(B)
b_agent.t_agent.mean.display_df_info_by_resid(save=True)

Write /home/user/workfolder/g4dna_protocol_demo/dsdna/d.fluctmatch/bigtraj_fluctmatch/0000_5000/result/bdna+bdna_HB.csv

In [12]:
## 確認機械熱點原子對的機械強度k_ij是否較高
b_agent.t_agent.mean.df_m.sort_values(by='k', ascending=False)

,Enm_i,Strand_i,Resid_i,Atomname_i,Atomid_i,Enm_j,Strand_j,Resid_j,Atomname_j,Atomid_j,k,b0,Category
PairID,,,,,,,,,,,,,
4066,A206,STRAND1,10,N2,206,B251,STRAND2,13,O2,716,15.250511,2.862353,hb
6527,A333,STRAND1,16,N2,333,B132,STRAND2,7,O2,597,15.226289,2.861616,hb
3183,A162,STRAND1,8,N2,162,B289,STRAND2,15,O2,754,14.850763,2.854363,hb
5620,A289,STRAND1,14,N2,289,B170,STRAND2,9,O2,635,14.613142,2.854011,hb
1632,A79,STRAND1,4,N2,79,B370,STRAND2,19,O2,835,14.542479,2.868316,hb
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3628,A184,STRAND1,9,N2,184,B268,STRAND2,14,N3,733,0.000000,3.690816,hb
3663,A185,STRAND1,9,N3,185,B268,STRAND2,14,N3,733,0.000000,5.090416,hb
3664,A185,STRAND1,9,N3,185,B270,STRAND2,14,O2,735,0.000000,4.931795,hb
3912,A201,STRAND1,10,C5,201,B249,STRAND2,13,N3,714,0.000000,5.114979,hb
144,A7,STRAND1,1,C8,7,B428,STRAND2,22,O2,893,0.000000,6.491684,hb